name: CI & Deploy (Pages)

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main ]   # run CI on PRs into main

permissions:
  contents: read
  pages: write
  id-token: write

# Prevent overlapping Pages deploys
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build (Next export)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      # IMPORTANT: fail hard in CI. Remove the "|| echo ok".
      - run: npm run content

      - run: npm run build

      # Upload the static site for deploy jobs
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  # Preview deploy for PRs and for the staging branch
  preview:
    name: Preview Deploy (PRs & staging)
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/staging'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
        with:
          preview: true  # publish as a preview URL
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

  # Production deploy only from main — and only if build passed
  deploy:
    name: Production Deploy (main)
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}