name: Staging Deployment

on:
    push:
        branches:
            - staging

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '18'
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build

    deploy:
        needs: build
        runs-on: ubuntu-latest
        if: success() # Only runs if build job succeeded
        steps:
            - uses: actions/checkout@v3
            # Add your deployment steps here
            - name: Deploy to Staging
              run: echo "Deploying to staging environment..."